import fs from "node:fs";
import path from "node:path";

const appRoot = path.resolve(process.cwd());
const legacySimplePushPath = path.resolve(appRoot, "../assets/js/simple-push.js");
const outEnvPath = path.resolve(appRoot, ".env.local");

function readFile(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

function extractFirebaseWebConfig(simplePushSource) {
  const block = simplePushSource.match(/const\s+firebaseConfig\s*=\s*\{([\s\S]*?)\};/);
  if (!block) return null;

  const config = {};
  const re = /(\w+)\s*:\s*["']([^"']+)["']\s*,?/g;
  let m;
  while ((m = re.exec(block[1])) !== null) {
    config[m[1]] = m[2];
  }

  const vapid = simplePushSource.match(/const\s+VAPID_KEY\s*=\s*['"]([^'"]+)['"]\s*;/);
  if (vapid?.[1]) config.vapidKey = vapid[1];

  return config;
}

function writeEnv(envObj) {
  const lines = [
    "# Generated by `npm run bootstrap:env`",
    "# Do not commit this file.",
    "",
    `NEXT_PUBLIC_DATA_BASE_URL=${envObj.dataBaseUrl}`,
    `NEXT_PUBLIC_AJAX_BASE_URL=${envObj.ajaxBaseUrl}`,
    `NEXT_PUBLIC_API_BASE_URL=${envObj.apiBaseUrl}`,
    "",
    `NEXT_PUBLIC_FIREBASE_API_KEY=${envObj.apiKey ?? "REPLACE_ME"}`,
    `NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${envObj.authDomain ?? "REPLACE_ME"}`,
    `NEXT_PUBLIC_FIREBASE_PROJECT_ID=${envObj.projectId ?? "REPLACE_ME"}`,
    `NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${envObj.storageBucket ?? "REPLACE_ME"}`,
    `NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${envObj.messagingSenderId ?? "REPLACE_ME"}`,
    `NEXT_PUBLIC_FIREBASE_APP_ID=${envObj.appId ?? "REPLACE_ME"}`,
    `NEXT_PUBLIC_FIREBASE_VAPID_KEY=${envObj.vapidKey ?? "REPLACE_ME"}`,
    ""
  ];

  fs.writeFileSync(outEnvPath, lines.join("\n"), "utf8");
}

if (!fs.existsSync(legacySimplePushPath)) {
  console.error(`Legacy file not found: ${legacySimplePushPath}`);
  console.error("Expected to read Firebase web config from ../assets/js/simple-push.js");
  process.exit(1);
}

const simplePush = readFile(legacySimplePushPath);
const extracted = extractFirebaseWebConfig(simplePush);
if (!extracted) {
  console.error("Could not find `const firebaseConfig = { ... }` in legacy simple-push.js");
  process.exit(1);
}

writeEnv({
  dataBaseUrl: "https://apps.dashify.com.au/milo/data",
  ajaxBaseUrl: "https://apps.dashify.com.au/milo/ajax",
  apiBaseUrl: "https://apps.dashify.com.au/milo/api",
  ...extracted
});

console.log(`Wrote ${outEnvPath}`);

